In [119]:
import pandas as pd 
import numpy as np

In [320]:
card = pd.read_csv("creditcard.csv")

In [321]:
card

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [322]:
non_fraud = card[card["Class"]==0]
fraud = card[card["Class"]==1]
non_fraud = non_fraud.sample(2*fraud.shape[0])
credit_card = fraud.append(non_fraud, ignore_index=True)

In [323]:
credit_card

Time        V1        V2        V3        V4        V5        V6  \
0        406.0 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545   
1        472.0 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823   
2       4462.0 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788   
3       6986.0 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536   
4       7519.0  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746   
...        ...       ...       ...       ...       ...       ...       ...   
1471   85012.0 -0.897650  0.953479  0.750672  0.286445  0.182449  0.046559   
1472  148361.0 -0.520989  1.742023 -1.095181  0.435068  0.778644 -1.499065   
1473   76736.0  1.447987 -0.612888  0.079566 -1.042673 -0.624725 -0.095486   
1474   50750.0 -1.287801  0.746940  2.146035  4.289066  0.304254  1.414431   
1475  142746.0  1.874601 -1.231523 -2.789120 -0.957333  0.025270 -1.270960   

            V7        V8        V9  ...       V21       V22       V23  \
0    -2.537387  1.391657 -2.770089  ...  0.517232 -0.035049 -0.465211   
1     0.325574 -0.067794 -0.270953  ...  0.661696  0.435477  1.375966   
2     0.562320 -0.399147 -0.238253  ... -0.294166 -0.932391  0.172726   
3    -3.496197 -0.248778 -0.247768  ...  0.573574  0.176968 -0.436207   
4     1.713445 -0.496358 -1.282858  ... -0.379068 -0.704181 -0.656805   
...        ...       ...       ...  ...       ...       ...       ...   
1471  0.454324  0.013262 -0.026719  ... -0.139108 -0.234294 -0.220593   
1472  0.699835  0.107225 -0.513625  ...  0.271245  0.766557 -0.333524   
1473 -0.775271  0.109005 -0.733171  ... -0.138203 -0.617470 -0.002674   
1474 -1.138951  0.881141 -1.929858  ...  0.385702  0.875792 -0.444412   
1475  0.617332 -0.532933 -1.187957  ...  0.012955  0.156686 -0.281694   

           V24       V25       V26       V27       V28  Amount  Class  
0     0.320198  0.044519  0.177840  0.261145 -0.143276    0.00      1  
1    -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00      1  
2    -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93      1  
3    -0.053502  0.252405 -0.657488 -0.827136  0.849573   59.00      1  
4    -1.632653  1.488901  0.566797 -0.010016  0.146793    1.00      1  
...        ...       ...       ...       ...       ...     ...    ...  
1471 -0.536815 -0.399569  0.361750 -0.542814 -0.133270   31.51      0  
1472 -0.218844 -0.268460 -0.011418 -0.012768  0.161680    1.00      0  
1473 -0.904664  0.306307 -0.420996 -0.004399 -0.002824    7.17      0  
1474 -0.783294 -0.436064  0.457580  0.024530 -0.056522    4.78      0  
1475 -0.371856  0.273568  1.631599 -0.213749 -0.083651  208.14      0  

[1476 rows x 31 columns]

In [324]:
credit_card.describe()

Time           V1           V2           V3           V4  \
count    1476.000000  1476.000000  1476.000000  1476.000000  1476.000000   
mean    89428.712737    -1.562264     1.203223    -2.354410     1.584688   
std     48767.686493     4.784288     3.320307     5.390895     2.911096   
min        41.000000   -30.552380   -19.337125   -31.103685    -3.914672   
25%     46726.000000    -1.914233    -0.348424    -2.927186    -0.445494   
50%     81634.000000    -0.447244     0.594205    -0.635081     0.659077   
75%    136658.500000     1.161234     1.770712     0.600752     2.999214   
max    172401.000000     2.368114    22.057729     3.417772    12.114672   

                V5           V6           V7           V8           V9  ...  \
count  1476.000000  1476.000000  1476.000000  1476.000000  1476.000000  ...   
mean     -1.058590    -0.474446    -1.845911     0.179962    -0.864591  ...   
std       3.577413     1.612638     4.992254     4.037609     2.065281  ...   
min     -22.105532    -7.361385   -43.557242   -41.044261   -13.434066  ...   
25%      -1.209413    -1.198170    -1.626390    -0.211021    -1.511340  ...   
50%      -0.299223    -0.509920    -0.298040     0.091445    -0.391465  ...   
75%       0.541801     0.234935     0.395885     0.658655     0.346312  ...   
max      11.095089     6.474115     7.376324    20.007208     6.437965  ...   

               V21          V22          V23          V24          V25  \
count  1476.000000  1476.000000  1476.000000  1476.000000  1476.000000   
mean      0.254628     0.000592    -0.023972    -0.051379     0.006891   
std       2.341897     1.047900     1.026943     0.579367     0.615472   
min     -22.797604    -8.887017   -19.254328    -2.307275    -4.781606   
25%      -0.202797    -0.546963    -0.216369    -0.391765    -0.327930   
50%       0.068940     0.011309    -0.026801     0.013115     0.025320   
75%       0.431149     0.575767     0.169197     0.373546     0.386337   
max      27.202839     8.361985     8.462485     1.247657     2.208209   

               V26          V27          V28       Amount        Class  
count  1476.000000  1476.000000  1476.000000  1476.000000  1476.000000  
mean      0.012827     0.052178     0.032554   104.997060     0.333333  
std       0.453837     0.879274     0.405716   265.260709     0.471564  
min      -1.349853    -7.263482    -3.320889     0.000000     0.000000  
25%      -0.283154    -0.060820    -0.048598     2.277500     0.000000  
50%      -0.033912     0.026891     0.024570    20.000000     0.000000  
75%       0.268746     0.272672     0.148093    94.820000     1.000000  
max       2.745261     3.849932     5.958241  3418.410000     1.000000  

[8 rows x 31 columns]

In [325]:
credit_card.isnull().any()

Time      False
V1        False
V2        False
V3        False
V4        False
V5        False
V6        False
V7        False
V8        False
V9        False
V10       False
V11       False
V12       False
V13       False
V14       False
V15       False
V16       False
V17       False
V18       False
V19       False
V20       False
V21       False
V22       False
V23       False
V24       False
V25       False
V26       False
V27       False
V28       False
Amount    False
Class     False
dtype: bool

In [326]:
credit_card.isnull()

Time     V1     V2     V3     V4     V5     V6     V7     V8     V9  \
0     False  False  False  False  False  False  False  False  False  False   
1     False  False  False  False  False  False  False  False  False  False   
2     False  False  False  False  False  False  False  False  False  False   
3     False  False  False  False  False  False  False  False  False  False   
4     False  False  False  False  False  False  False  False  False  False   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
1471  False  False  False  False  False  False  False  False  False  False   
1472  False  False  False  False  False  False  False  False  False  False   
1473  False  False  False  False  False  False  False  False  False  False   
1474  False  False  False  False  False  False  False  False  False  False   
1475  False  False  False  False  False  False  False  False  False  False   

      ...    V21    V22    V23    V24    V25    V26    V27    V28  Amount  \
0     ...  False  False  False  False  False  False  False  False   False   
1     ...  False  False  False  False  False  False  False  False   False   
2     ...  False  False  False  False  False  False  False  False   False   
3     ...  False  False  False  False  False  False  False  False   False   
4     ...  False  False  False  False  False  False  False  False   False   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...     ...   
1471  ...  False  False  False  False  False  False  False  False   False   
1472  ...  False  False  False  False  False  False  False  False   False   
1473  ...  False  False  False  False  False  False  False  False   False   
1474  ...  False  False  False  False  False  False  False  False   False   
1475  ...  False  False  False  False  False  False  False  False   False   

      Class  
0     False  
1     False  
2     False  
3     False  
4     False  
...     ...  
1471  False  
1472  False  
1473  False  
1474  False  
1475  False  

[1476 rows x 31 columns]

In [327]:
train = credit_card.sample(frac=0.5, random_state=1)

In [328]:
credit_card = credit_card.drop(train.index)

In [329]:
val_data = credit_card.sample(frac=0.4, random_state=1)

In [330]:
val_data.shape

(295, 31)

In [331]:
test = credit_card.drop(val_data.index)

In [332]:
train

Time        V1        V2        V3        V4        V5        V6  \
575   123273.0 -1.007242  0.498596  0.219791 -2.057640 -1.325857 -0.969320   
390   135095.0  0.232512  0.938944 -4.647780  3.079844 -1.902655 -1.041408   
826   156053.0  1.546912 -1.246097 -1.062565 -0.000486 -0.412679  0.300340   
341   102542.0 -1.456876  3.740306 -7.404518  7.440964 -1.549878 -1.661697   
984   120075.0  2.169498 -1.081440 -1.003399 -1.192692 -0.452339  0.346489   
...        ...       ...       ...       ...       ...       ...       ...   
1422  162103.0  0.624508  0.911228 -0.798883  0.578402  1.137133 -0.659458   
1173   40544.0 -0.822267 -0.271979  0.597894 -3.173244  1.610471  3.450573   
820    60880.0 -0.402028 -0.281214  1.261573 -0.925637  0.011157  1.274702   
448   152802.0  1.322724 -0.843911 -2.096888  0.759759 -0.196377 -1.166353   
1392  154106.0  0.053027  0.651778 -0.358235 -0.590768  1.251568 -0.136382   

            V7        V8        V9  ...       V21       V22       V23  \
575  -0.805255  0.860990 -0.537964  ...  0.350059  0.871073 -0.124906   
390  -1.020407  0.547069 -1.105990  ...  0.911373  1.042929  0.999394   
826  -0.320159  0.146817  1.144311  ... -0.099347 -0.817860  0.150139   
341  -5.757213  1.615011 -2.194881  ...  0.957897  0.145339 -0.044704   
984  -1.063000  0.063144 -0.115059  ...  0.308375  0.941014 -0.064230   
...        ...       ...       ...  ...       ...       ...       ...   
1422  1.573043 -0.697689 -0.761683  ...  0.264010  1.109292 -0.145873   
1173 -0.420871  0.899889 -1.311838  ... -0.514603 -1.347119 -0.047931   
820   0.677114  0.025056 -1.138505  ... -0.039047  0.468689  0.107743   
448   0.482534 -0.349791  1.045007  ...  0.133815 -0.121562 -0.208574   
1392  0.889675 -0.070207  0.347214  ... -0.167635 -0.246756 -0.074760   

           V24       V25       V26       V27       V28  Amount  Class  
575   0.032868  0.281799 -0.150687  0.085787 -0.079480   19.95      0  
390   0.901260 -0.452093  0.192959  0.180859 -0.029315  345.00      1  
826   0.044412 -0.557810 -0.362032 -0.056880 -0.006073  250.00      0  
341  -0.544962 -0.757757 -0.005352  0.318152 -0.323554    2.28      1  
984  -1.391493 -0.000770 -0.020774  0.007895 -0.067864   32.37      0  
...        ...       ...       ...       ...       ...     ...    ...  
1422  0.675705 -0.706218  0.467457  0.061649  0.019721   36.54      0  
1173  1.008537 -0.004322  1.122106 -0.176771  0.073187   54.00      0  
820  -1.166018 -0.418656 -0.478961  0.041519 -0.033863  158.00      0  
448  -0.254752 -0.098324 -0.613874  0.002654  0.072386  357.95      1  
1392  0.025805 -0.814276 -0.191729  0.042246  0.022894   15.00      0  

[738 rows x 31 columns]

In [333]:
train_labels = train['Class']    

In [334]:
train_labels

575     0
390     1
826     0
341     1
984     0
       ..
1422    0
1173    0
820     0
448     1
1392    0
Name: Class, Length: 738, dtype: int64

In [335]:
test_labels = test.iloc[:,-1]   
val_labels = val_data.iloc[:,-1]   

In [336]:
train = train.drop(columns='Class')
test = test.drop(columns='Class')
val_data = val_data.drop(columns='Class')

In [337]:
train.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
dtype: object

In [338]:
mean = train.mean()
train -= mean
std = train.std()
train /= std
test /= std
val_data/=std

In [339]:
import keras 
import tensorflow as tf

In [340]:
from keras import models, layers
model = models.Sequential([
    (layers.Dense(10, activation='relu', input_shape=(train.shape[1],))),
#     (layers.Dropout(0.5)),
    (layers.Dense(8, activation='relu')),
#     (layers.Dropout(0.5)),
    (layers.Dense(6, activation='relu')),
#     (layers.Dropout(0.5)),
    (layers.Dense(1,  activation = 'sigmoid'))
])


In [341]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(train, train_labels, epochs=100,validation_data=(val_data, val_labels))
# results = model.evaluate(test, test_labels)

Train on 738 samples, validate on 295 samples
Epoch 1/100
738/738 [==============================] - 5s 6ms/step - loss: 0.6433 - accuracy: 0.7019 - val_loss: 0.5986 - val_accuracy: 0.7322
Epoch 2/100
738/738 [==============================] - 0s 431us/step - loss: 0.5425 - accuracy: 0.7696 - val_loss: 0.5382 - val_accuracy: 0.8034
Epoch 3/100
738/738 [==============================] - 0s 283us/step - loss: 0.4644 - accuracy: 0.7995 - val_loss: 0.4745 - val_accuracy: 0.8508
Epoch 4/100
738/738 [==============================] - 0s 273us/step - loss: 0.3871 - accuracy: 0.8279 - val_loss: 0.4380 - val_accuracy: 0.8373
Epoch 5/100
738/738 [==============================] - 0s 249us/step - loss: 0.3252 - accuracy: 0.8659 - val_loss: 0.4313 - val_accuracy: 0.8034
Epoch 6/100
738/738 [==============================] - 0s 225us/step - loss: 0.2789 - accuracy: 0.9092 - val_loss: 0.4621 - val_accuracy: 0.7559
Epoch 7/100
738/738 [==============================] - 0s 254us/step - loss: 0.2456 - 

Epoch 57/100
738/738 [==============================] - 0s 113us/step - loss: 0.0672 - accuracy: 0.9810 - val_loss: 1.3869 - val_accuracy: 0.5492
Epoch 58/100
738/738 [==============================] - 0s 127us/step - loss: 0.0671 - accuracy: 0.9756 - val_loss: 1.3891 - val_accuracy: 0.5627
Epoch 59/100
738/738 [==============================] - 0s 150us/step - loss: 0.0656 - accuracy: 0.9783 - val_loss: 1.4446 - val_accuracy: 0.5458
Epoch 60/100
738/738 [==============================] - 0s 113us/step - loss: 0.0641 - accuracy: 0.9783 - val_loss: 1.4490 - val_accuracy: 0.5458
Epoch 61/100
738/738 [==============================] - 0s 111us/step - loss: 0.0624 - accuracy: 0.9810 - val_loss: 1.4941 - val_accuracy: 0.5424
Epoch 62/100
738/738 [==============================] - 0s 91us/step - loss: 0.0615 - accuracy: 0.9797 - val_loss: 1.5623 - val_accuracy: 0.5322
Epoch 63/100
738/738 [==============================] - 0s 85us/step - loss: 0.0604 - accuracy: 0.9837 - val_loss: 1.5715 - v

In [342]:
results = model.evaluate(test, test_labels)

443/443 [==============================] - 0s 57us/step


In [343]:
results

[2.0584008963841685, 0.5711060762405396]

In [357]:
test_labels

1       1
4       1
16      1
18      1
22      1
       ..
1458    0
1465    0
1471    0
1474    0
1475    0
Name: Class, Length: 443, dtype: int64

In [359]:
x = model.predict(test)

In [360]:
x.max()

1.0

In [366]:
x[22]

array([0.9910856], dtype=float32)

In [291]:
x>0.9

array([[False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [317]:
x[8]

array([1.], dtype=float32)

In [231]:
for j,i in enumerate(x):
    if i>=1:
        print(j,i)
        

0 [1.]


In [148]:
model.predict(np.array(test.iloc[5,:]).reshape(1,test.shape[1]))

array([[5.9249796e-06]], dtype=float32)

array([[0.00287909]], dtype=float32)